### ISSUE TITLE
Ơ kìa, web sập rồi à

### ISSUE THREAD

**Issue by thatfrozenfrog** [zennomi/truyendex#3]
Vào nettrom báo lỗi 502 ạ
![image](https://github.com/zennomi/truyendex/assets/101154752/9479ce22-7e88-49b5-acb6-71a9a2d137f7)
¯\_(ツ)_/¯

**Comment by Hinatara** [comment]
Dùng 1.1.1.1 thử xem

**Comment by zennomi** [comment]
Tái khởi động ở domain mới là [truyendex.com](https://truyendex.com/) nha
