### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Satellaa** [zennomi/truyendex#6]
liệu Zennomi sẽ thêm TruyenDex API trong tương lai hay điều này chưa từng là một mục tiêu?

**Comment by Satellaa** [comment]
ngoài ra Zennomi có cho phép các bên thứ 3 cào TruyenDex trong lúc chưa có  API?

**Comment by lelinhtinh** [comment]
1. Sao lại đi đường vòng mà không lấy trực tiếp từ MangaDex API?
2. Đã cào thì sao phải hỏi.

**Comment by Satellaa** [comment]
1. Bởi vì TruyenDex không chỉ lấy từ MangaDex đó bạn

**Comment by zennomi** [comment]
Với data manga, TruyenDex hiện tại chỉ lấy từ API của MangaDex. Muốn cào data thì bạn qua thẳng MangaDex mà cào thôi bạn.
